
UPDATE [lmgm].[PAGE]
SET
   [PAGE_CONFIG] = '{"layout":"defaultLayout","imports":[],"body":[{"type":"mgmIllustration","config":{"image":"{baseUrl}/assets/images/hurray.svg","imageAlt":"Hi","alignment":"center","style":{"unit-of-measure-width":"%","unit-of-measure-padding-right":"%","unit-of-measure-padding-left":"%","width":"90","padding-right":"5","padding-left":"5","height":"300","unit-of-measure-height":"px"}},"id":0},{"type":"markdown","config":{"content":"### Invite Friends &#129505;","style":{"padding-top":"0","unit-of-measure-padding-top":"px","padding-right":"10","unit-of-measure-padding-right":"px","padding-left":"10","unit-of-measure-padding-left":"px"}},"id":1},{"type":"markdown","config":{"content":"Love banking with us? Invite a friend to open an account and both of you will earn PHP 500!\n\n[Learn More >](event:navigate;pageTitle:Invite Friends;navigationStyle:open;targetPage:13;)","style":{"color":"#8C8C8C","padding-top":"20","unit-of-measure-padding-top":"px","padding-right":"10","unit-of-measure-padding-right":"px","padding-left":"10","unit-of-measure-padding-left":"px","font-size":"14","unit-of-measure-font-size":"px"}},"id":2}],"footer":[{"type":"markdown","config":{"content":"By allowing ING access to your contacts, you agree to Invite friends'' [Terms & Conditions.](event:navigate;navigationStyle:open;targetPage:25;pageTitle:Terms & Conditions) Your contacts won''t be used for any other purposes.","style":{"unit-of-measure-padding-right":"px","unit-of-measure-padding-left":"px","unit-of-measure-font-size":"px","font-size":"14","color":"#696969","padding-right":"10","padding-left":"10","unit-of-measure-margin-bottom":"em","margin-bottom":"1"}},"id":0},{"type":"mobileButton","config":{"label":"Invite Friends","buttonType":"","color":"","click":{"type":"customEvent","config":{"eventName":"sync-contact-list","data":{"customKey":"customVal"}}},"style":{"unit-of-measure-width":"%","width":"100"}},"id":1}],"dialog":[],"version":1,"view":"mobile","lifecycle":{"load":[{"type":"","config":{}}]},"userId":"602f2d0a82f1190580f25bbe"}'
WHERE
[ID] = '10'
GO

UPDATE [lmgm].[PAGE]
SET
   [PAGE_CONFIG] = '{"layout":"defaultLayout","body":[{"type":"mgmIllustration","config":{"image":"{baseUrl}/assets/images/hurray.svg","imageAlt":"Hi","alignment":"center","style":{"unit-of-measure-width":"%","width":"80","height":"300","unit-of-measure-height":"px"}},"id":0},{"type":"markdown","config":{"content":"Love banking with us?<br>Invite a friend to open an account and both of you will earn PHP 500!<br>Get your reward with these easy steps.","style":{"font-size":"20","unit-of-measure-font-size":"px","text-align":"center","padding-top":"0","unit-of-measure-padding-top":"px","padding-bottom":"0","unit-of-measure-padding-bottom":"px","padding-right":"9","unit-of-measure-padding-right":"px","padding-left":"9","unit-of-measure-padding-left":"px"}},"id":1},{"type":"mgmNumberList","config":{"listContent":[{"title":"Sync your contacts","content":"Allow ING to access your contacts so we can recognize the friends you’ll invite by their mobile numbers."},{"title":"Invite a friend","content":"Send a friend an invite with a link to download the ING app."},{"title":"Earn your reward!","content":"After your friend funds their verified ING account with at least PHP 1,000, both of you will get PHP 500. <br><br> Your friend''s funds must come from a deposited check or be transferred from another bank."}],"style":{"unit-of-measure-padding-top":"px","unit-of-measure-padding-right":"px","unit-of-measure-padding-left":"px","unit-of-measure-padding-bottom":"px","padding-top":"20","padding-right":"19","padding-bottom":"0","padding-left":"0"}},"id":2},{"type":"markdown","config":{"content":"You can invite up to 10 friends every month! Sync your contacts and start sending those invites now!","style":{"color":"#8C8C8C","padding-top":"0","unit-of-measure-padding-top":"px","padding-right":"10","unit-of-measure-padding-right":"px","padding-left":"10","unit-of-measure-padding-left":"px"}},"id":3}],"footer":[{"type":"markdown","config":{"content":"By allowing ING access to your contacts, you agree to Invite friends'' [Terms & Conditions.](event:navigate;navigationStyle:open;targetPage:25;pageTitle:Terms & Conditions) Your contacts won’t be used for any other purposes.","style":{"unit-of-measure-padding-right":"px","unit-of-measure-padding-left":"px","unit-of-measure-font-size":"px","font-size":"14","color":"#696969","padding-right":"10","padding-left":"10","unit-of-measure-margin-bottom":"em","margin-bottom":"1"}},"id":0},{"type":"mobileButton","config":{"label":"Invite Friends","click":{"type":"customEvent","config":{"eventName":"sync-contact-list","data":{"customKey":"customVal"}}},"style":{"unit-of-measure-width":"%","width":"100"}},"id":1}],"view":"mobile","lifecycle":{"load":[{"type":"","config":{}}]},"userId":"602f2d0a82f1190580f25bbe"}'
WHERE
[ID] = '13'
GO

UPDATE [lmgm].[PAGE]
SET
   [PAGE_CONFIG] = '{"layout":"defaultLayout","body":[{"type":"mgmIllustration","config":{"image":"{baseUrl}/assets/images/Member%20Get%20Member.svg","imageAlt":"Hi","alignment":"center","style":{"padding-top":"60","unit-of-measure-padding-top":"px","width":"100","unit-of-measure-width":"%"}},"id":0},{"type":"markdown","config":{"content":"### You have chosen {displayName} as your referrer!","style":{"unit-of-measure-padding-top":"px","unit-of-measure-padding-right":"px","padding-bottom":"0","unit-of-measure-padding-bottom":"px","unit-of-measure-padding-left":"px","padding-right":"5.5","padding-left":"5.5","padding-top":"45.21"}},"id":1},{"type":"markdown","config":{"content":"Fund your account with a minimum of PHP 1000, so you both can get PHP 500. &#127881; <br><br> The funds must be from a deposited check or a transfer from another bank.","style":{"padding-right":"5.5","padding-left":"5.5","unit-of-measure-padding-right":"px","unit-of-measure-padding-left":"px","unit-of-measure-padding-top":"px","padding-top":"25"}},"id":2}],"footer":[{"type":"mobileButton","config":{"label":"BACK TO PROFILE","buttonType":"","color":"","click":{"type":"customEvent","config":{"eventName":"back-to-profile","data":{"customKey":"customVal"}}},"style":{"unit-of-measure-width":"%","unit-of-measure-margin-top":"px","width":"100","margin-top":"30"}},"id":0}],"view":"mobile","lifecycle":{"load":[{"type":"","config":{}}]},"userId":"602f2d0a82f1190580f25bbe"}'
WHERE
[ID] = '63'
GO